### ISSUE TITLE
Error thrown in voice activity

### ISSUE THREAD

**Issue by FelixRandle** [FelixRandle/Sheffield-Discord-Bot#48]
```
4|Discord  | Traceback (most recent call last):
4|Discord  |   File "/usr/local/lib/python3.6/dist-packages/orator/connections/connection.py", line 32, in _run
4|Discord  |     result = wrapped(self, query, bindings, *args, **kwargs)
4|Discord  |   File "/usr/local/lib/python3.6/dist-packages/orator/connections/connection.py", line 265, in statement
4|Discord  |     return self._new_cursor().execute(query, bindings)
4|Discord  |   File "/usr/local/lib/python3.6/dist-packages/MySQLdb/cursors.py", line 209, in execute
4|Discord  |     res = self._query(query)
4|Discord  |   File "/usr/local/lib/python3.6/dist-packages/MySQLdb/cursors.py", line 315, in _query
4|Discord  |     db.query(q)
4|Discord  |   File "/usr/local/lib/python3.6/dist-packages/MySQLdb/connections.py", line 239, in query
4|Discord  |     _mysql.connection.query(self, query)
4|Discord  | MySQLdb._exceptions.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`sheffieldcompsci`.`voice`, CONSTRAINT `voice_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`))')
4|Discord  |
4|Discord  | During handling of the above exception, another exception occurred:
4|Discord  |
4|Discord  | Traceback (most recent call last):
4|Discord  |   File "/usr/local/lib/python3.6/dist-packages/discord/ext/tasks/__init__.py", line 120, in _loop
4|Discord  |     raise exc
4|Discord  |   File "/usr/local/lib/python3.6/dist-packages/discord/ext/tasks/__init__.py", line 98, in _loop
4|Discord  |     await self.coro(*args, **kwargs)
4|Discord  |   File "/data/Sheffield-Discord-Bot/cogs/logging.py", line 140, in voice_channel_check
4|Discord  |     guild_id=guild.id)
4|Discord  |   File "/usr/local/lib/python3.6/dist-packages/orator/orm/model.py", line 461, in first_or_create
4|Discord  |     return cls.create(**attributes)
4|Discord  |   File "/usr/local/lib/python3.6/dist-packages/orator/orm/model.py", line 422, in create
4|Discord  |     model.save()
4|Discord  |   File "/usr/local/lib/python3.6/dist-packages/orator/orm/model.py", line 1630, in save
4|Discord  |     saved = self._perform_insert(query, options)
4|Discord  |   File "/usr/local/lib/python3.6/dist-packages/orator/orm/model.py", line 1701, in _perform_insert
4|Discord  |     self._insert_and_set_id(query, attributes)
4|Discord  |   File "/usr/local/lib/python3.6/dist-packages/orator/orm/model.py", line 1723, in _insert_and_set_id
4|Discord  |     id = query.insert_get_id(attributes, key_name)
4|Discord  |   File "/usr/local/lib/python3.6/dist-packages/orator/orm/builder.py", line 1179, in call
4|Discord  |     result = attribute(*args, **kwargs)
4|Discord  |   File "/usr/local/lib/python3.6/dist-packages/orator/query/builder.py", line 1400, in insert_get_id
4|Discord  |     return self._processor.process_insert_get_id(self, sql, values, sequence)
4|Discord  |   File "/usr/local/lib/python3.6/dist-packages/orator/query/processors/mysql_processor.py", line 28, in process_insert_get_id
4|Discord  |     query.get_connection().insert(sql, values)
4|Discord  |   File "/usr/local/lib/python3.6/dist-packages/orator/connections/connection.py", line 250, in insert
4|Discord  |     return self.statement(query, bindings)
4|Discord  |   File "/usr/local/lib/python3.6/dist-packages/orator/connections/connection.py", line 35, in _run
4|Discord  |     e, query, bindings, wrapped
4|Discord  |   File "/usr/local/lib/python3.6/dist-packages/orator/connections/connection.py", line 357, in _try_again_if_caused_by_lost_connection
4|Discord  |     raise QueryException(query, bindings, e)
4|Discord  | orator.exceptions.query.QueryException: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`sheffieldcompsci`.`voice`, CONSTRAINT `voice_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`))') (SQL: INSERT INTO `voice` (`guild_id`, `user_id`) VALUES (%s, %s) ([612377874787336212, 234395307759108106]))
```

**Comment by FelixRandle** [comment]
Fixed in #49
